### ISSUE TITLE
Consider making `quarkus.qpid-jms.url` optional

### ISSUE THREAD

**Issue by jamesnetherton** [amqphub/quarkus-qpid-jms#11]
In camel-quarkus we leverage `quarkus-qpid-jms` in our [`camel-quarkus-amqp`](https://camel.apache.org/camel-quarkus/latest/reference/extensions/amqp.html) extension to provide the AMQP client, `ConnectionFactory` bean, native support etc.

Camel has some alternative configuration methods for setting up the AMQP component that we'd like to preserve:

https://camel.apache.org/components/latest/amqp-component.html#_configuring_amqp_component

The problem is that since `quarkus.qpid-jms.url` is mandatory, it makes the UX slightly trickier because folks are forced to provide config property when it is potentially not always required.

Can we make `quarkus.qpid-jms.url` optional and not produce the `ConnectionFactory` bean if it is not present?

**Comment by jamesnetherton** [comment]
@gemmellr Is this something that could be considered for the next release?

**Comment by gemmellr** [comment]
Sorry, @jamesnetherton , I've been off work.

If the value isn't present, which is only really detectable for sure at runtime, you suggest just to spot this and not to create the factory. That meaning to return null? This issue was referenced from quarkusio/quarkus#18231 which the comments on seems to suggest producing a null result is frowned upon?

I think instead it might make more sense to consider making the value optional but then actually having a default value, e.g _amqp://localhost:5672_. I think that would that still work for your use cases if I understand correctly?

**Comment by gemmellr** [comment]
Aside, I see just below configuration bits you linked to that the 'topics' bit https://camel.apache.org/components/latest/amqp-component.html#_using_topics indicates camel automatically configures a 'topic prefix' for many of the configuration routes which were shown (whilst another is shown doing it manually, noting its for ActiveMQ).

The ActiveMQ 5 broker has for several years advertised its queue and topic prefixes upon connection (since 5.11 in early 2015 I believe). Every version of qpid-jms-client has looked for that detail and if found then adds it automatically itself, so doing that configuration should be unnecessary these days. Meanwhile, by setting the prefix explicitly all the time you will be introducing unexpected prefixing when being used with any other AMQP 1.0 server besides ActiveMQ 5, even though that server doesnt actually need or want it.

I also see the 'Enabling AMQP specific options' section links to the Qpid JMS 0.51.0 docs. Thats a bit stale, the current version is 1.1.0, or else 0.59.0 if still needing Java 8 support.

**Comment by gemmellr** [comment]
@jamesnetherton I've raised #14 around making it optional via a default. Let me know if that works for you, if it does I'd include it in the next release (tomorrow I think, if Quarkus schedule holds).

**Comment by jamesnetherton** [comment]
Thanks for the feedback @gemmellr! Hold fire on the fix for now. I just read through the linked Artemis extension issue and it seems Stuart is [proposing](https://github.com/quarkusio/quarkus/issues/18231#issuecomment-881179940) a way of possibly making this a bit cleaner to implement. But it needs to be proven whether it's a viable option first.

**Comment by gemmellr** [comment]
The outstanding issue for the Artemis extension seems to centre around its health check stuff also using the property, which isnt an issue in this case (and wont be; there are many cases it isnt possible to use the exact same factory URL value for another use, so I simply wouldnt) so I think we can consider this independently.

**Comment by jamesnetherton** [comment]
Ah sorry, I misinterpreted what Stuart was referring to. So lets proceed with #14.

**Comment by gemmellr** [comment]
I have merged the PR for inclusion in the 0.26.0 release.

**Comment by gemmellr** [comment]
0.26.0 is now released and on central
