### ISSUE TITLE
Quarkus JMS tutorial contains test that always fails

### ISSUE THREAD

**Issue by maxkahan** [amqphub/quarkus-qpid-jms#17]
When creating a Maven project in the Qpid JMS tutorial [here](https://quarkus.io/guides/jms#creating-the-maven-project) the command

`mvn io.quarkus.platform:quarkus-maven-plugin:2.4.1.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=jms-quickstart \
    -DclassName="org.acme.jms.PriceResource" \
    -Dpath="/prices" \
    -Dextensions="resteasy,qpid-jms"`

creates a PriceResource.java file and auto-generates a test in the file PriceResourceTest.java.

The tutorial then asks a user to overwrite the contents of the PriceResource.java file https://quarkus.io/guides/jms#the-price-resource which means the auto-generated test will never pass.

To get the code working, I had to delete the PriceResourceTest.java file and the compiled test, or keep in the restEasy code in the PriceResource.java file, which is not explained in the tutorial.

**Comment by gemmellr** [comment]
The Quarkus guides are maintained in the main quarkus repository (and then synced with the website repo for publish).

The issue is that the command creates the class (which the guide then says to create), which also creates the test. I have raised a PR at Quarkus to update the command to explicitly not create the generated code, you can follow the progress there:
https://github.com/quarkusio/quarkus/pull/21364
