### ISSUE TITLE
The client's failover provider did not fire the connection ExceptionListener

### ISSUE THREAD

**Issue by 15I** [amqphub/quarkus-qpid-jms#2]
The client's failover provider did not fire the connection ExceptionListener (MessageConsumer) when connection to the broker is lost.

Environment:
application.properties:
...
connection.uri = failover:(amqp://${messaging.service.host}:${messaging.service.port})
...

Quarkus 1.0.1.Final
Quarkus extensions:
quarkus-smallrye-opentracing
quarkus-qpid-jms (Version 0.8.2)

Quarkus Installed features: [cdi, jaeger, qpid-jms, resteasy, smallrye-opentracing]

**Comment by gemmellr** [comment]
It wont fire if it is trying to reconnect, which you have configured it to by using a failover uri. It doesnt fire on every drop since the typical response to the exception listener firing is just to close the connection, defeating the point. It will fire the listener when it runs out of failover attempts, but in this case you haven't configured a limit. You could try either configuring some limits, or if you want an exception on each drop you can use a non-failover connection configuration.
