### ISSUE TITLE
multiple URL connections

### ISSUE THREAD

**Issue by 15I** [amqphub/quarkus-qpid-jms#3]
Is it possible to have more than one URL connections (incoming, outgoing)?

**Comment by gemmellr** [comment]
The extension only facilitates ConnectionFactory injection based on a single connection URL. The resulting ConnectionFactory could be used to create multiple Connections, but they would still use the same URL config.

I understand that it might be possible for you to override and replace how the factory is actually produced by the extension since the method is annotated @DefaultBean, https://github.com/amqphub/quarkus-qpid-jms/blob/0.11.2/runtime/src/main/java/org/amqphub/quarkus/qpid/jms/runtime/QpidJmsProducer.java#L34, so perhaps its possible you can customise it to your needs somehow, but this isnt an area I have any experience with.

I believe you also used the extension before the injection bit was very recently added; I'd expect you can continue to use it with directly instantiating the clients ConnectionFactory as you would have done before and continue to use different URLs via application config properties as you presumably already did.

**Comment by 15I** [comment]
I am using this extension with multiple Connections, but now to make it work the required config property must be added although it is not in use.

**Comment by gemmellr** [comment]
Ah I see. I admit that isnt something I had considered when adding that. However I think the current setup matches what many users will need and expect, plus it aligns with an existing JMS extension in Quarkus, so I think it makes sense to retain the new behaviour.
